version: "3.7"
services:
    nginx-proxy:
        image: nginx:latest
        container_name: nginx-proxy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/nginx-proxy:/etc/nginx/conf.d
            - ./data/ssl:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        depends_on: 
            - nginx
        networks:
            - web-net 

    nginx:
        image: nginx:latest
        container_name: nginx-server
        restart: always
        volumes:
            - ./data/vhosts:/etc/nginx/conf.d
            - ./data/www:/var/www
        depends_on:
            - php
            - mariadb
        networks:
            - web-net
        
    php:
        build:
            context: .
            dockerfile: php7-fpm-alt
        container_name: php
        restart: always
        volumes:
            - ./data/www:/var/www
        depends_on:
            - mariadb
        networks:
            - web-net

    mariadb:
        image: mariadb
        container_name: mariadb
        restart: always
        ports:
            - "49155:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: <MYSQL_ROOT_PASS>
        networks:
            - web-net

    redis:
        image: redis:alpine
        container_name: redis
        command: redis-server --requirepass <REDIS_PASS> 
        volumes:
            - ./data/redis/redis_data:/var/lib/redis
            - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_REPLICATION_MODE=master
        networks:
            - web-net     

networks:
    web-net:
        name: web-net
        driver: bridge
